
project_id = "teniefzxdikestahdnur"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://891c3d8d-9dae-4a89-93b0-4ac028ad75b8.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = true
enable_email_autoconfirm = false

[auth.email]
enable_signup = true
double_confirm_changes_enabled = true
enable_confirmations = true
template = {}
smtp = {}

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"

[edge_runtime]
enabled = true
port = 54329
inspector_port = 54330

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.ai-marketing-analysis]
verify_jwt = true

[functions.send-custom-email]
verify_jwt = false

